url_steam_games     = "https://api.steampowered.com/ISteamApps/GetAppList/v0002/?format=json"
json_steam_games    = "all_games.json"
url_game_info       = "https://store.steampowered.com/api/appdetails?appids="
json_game_info      = "appdetails"
url_game_store_page = "https://store.steampowered.com/app/"
db_path             = "steam.db"
ignored_game_att    = [
    'short_description',
    'detailed_description',
    'about_the_game',
    'supported_languages',
    'pc_requirements',
    'mac_requirements',
    'linux_requirements',
    'screenshots',
    'movies',
    'background',
    'background_raw',
    'achievements',
    'content_descriptors',
    'package_groups',
    'recomendations'
]
